### ISSUE TITLE
StaleElementReferenceException

### ISSUE THREAD

**Issue by pulberg** [tntlt/getawscred#1]
Hi there, I'm getting the following error using the script - 

```
python3 getawscred.py myurl.awsapps.com myuser "myaccount" "myrole" -p myprofile
Enter password:
Traceback (most recent call last):
  File "getawscred.py", line 189, in <module>
    run_program()
  File "getawscred.py", line 120, in run_program
    record.send_keys(record_input)
  File "/home/pulberg/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "/home/pulberg/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/pulberg/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pulberg/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=90.0.4430.93)
```

**Comment by tntlt** [comment]
See if you have the same screen with the same elements once you enter username manually in browser (screenshot attached).
Also try do 'pkill -9 chrome' before running app.
![Capture_1](https://user-images.githubusercontent.com/6333930/116624417-e23d2f00-a915-11eb-9f8a-864886296a6a.PNG)

**Comment by pulberg** [comment]
Yes, I have those elements


![Screen Shot 2021-04-29 at 6 12 52 PM](https://user-images.githubusercontent.com/11069351/116630752-7066e480-a919-11eb-8a32-933824d4355c.png)

Also, i'm not sure if it is related, but the process is taking nearly 5min - 

```
real    4m35.997s
user    0m0.170s
sys     0m0.026s
```

**Comment by tntlt** [comment]
Strange, it should not take more than 2 min even with MFA. The app has a 2sec timeouts after each input (which you may remove), due not enough time for page refresh. Make sure your machine is powerful enough to run chrome in background. 
![Capture_2](https://user-images.githubusercontent.com/6333930/116637095-ff332b80-a930-11eb-870a-50e29d6bcc2c.PNG)

**Comment by pulberg** [comment]
The machine is a new 8 core i9 with 64gb mem MBP, i'm running the script inside an Ubuntu 20 vm that i have allocated 8 cores and 8gb mem.  For kicks i turned off my corp vpn and now get this - 

```
Traceback (most recent call last):
  File "getawscred.py", line 189, in <module>
    run_program()
  File "getawscred.py", line 109, in run_program
    record.clear()
AttributeError: 'NoneType' object has no attribute 'clear'

real    2m23.253s
user    0m0.144s
sys     0m0.027s
```

**Comment by pulberg** [comment]
i got this working by increasing each 2sec sleep to 30sec.
